"use client";
import { FormEvent, useState } from "react";
type Message = { role: "user" | "assistant"; content: string };
export default function ClinicChatbot() {
  const [open, setOpen] = useState(false), [input, setInput] = useState(""), [loading, setLoading] = useState(false);
  const [messages, setMessages] = useState<Message[]>([{ role: "assistant", content: "أهلاً بك 🌿\nأگدر أساعدك بمعلومات الدوام، الموقع، الحجز أو التواصل مع العيادة." }]);
  const send = async (event?: FormEvent, preset?: string) => { event?.preventDefault(); const content = (preset || input).trim(); if (!content || loading) return; const next = [...messages, { role: "user" as const, content }]; setMessages(next); setInput(""); setLoading(true); try { const r = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: next }) }); const d = await r.json(); setMessages([...next, { role: "assistant", content: d.message || "تعذر الرد حالياً." }]); } catch { setMessages([...next, { role: "assistant", content: "تعذر الاتصال حالياً. تواصل معنا عبر واتساب." }]); } finally { setLoading(false); } };
  return <><button className="chat-trigger" onClick={() => setOpen(true)} aria-label="فتح مساعد العيادة"><span>✦</span><b>مساعد العيادة</b></button>{open && <div className="chat-overlay" onMouseDown={(e) => { if (e.target === e.currentTarget) setOpen(false); }}><section className="chat-panel" role="dialog" aria-modal="true" aria-labelledby="chat-title"><header className="chat-header"><div><span className="chat-status" /><strong id="chat-title">مساعد العيادة</strong><small>متاح لمساعدتك</small></div><button onClick={() => setOpen(false)} aria-label="إغلاق">×</button></header><div className="chat-messages">{messages.map((m, i) => <div className={`chat-message ${m.role}`} key={i}>{m.content}</div>)}{loading && <div className="chat-message assistant">جاري التفكير…</div>}</div><div className="chat-shortcuts"><button onClick={() => send(undefined, "ما هي أوقات الدوام؟")}>أوقات الدوام</button><button onClick={() => send(undefined, "أين موقع العيادة؟")}>الموقع</button><button onClick={() => send(undefined, "أريد حجز موعد")}>الحجز</button></div><form className="chat-form" onSubmit={send}><input value={input} onChange={(e) => setInput(e.target.value)} placeholder="اكتب سؤالك هنا…" aria-label="رسالتك" /><button type="submit" disabled={loading || !input.trim()} aria-label="إرسال">↑</button></form><a className="chat-whatsapp" href="https://wa.me/9647707960430" target="_blank" rel="noreferrer">تواصل مباشرة عبر واتساب</a></section></div>}</>;
}
